<?php

namespace App\Contracts;

use App\Models\Order;
use App\Models\CheckoutToken;
use App\Services\Payment\PaymentResult;
use App\Services\Payment\PaymentService;
use Illuminate\Http\Request;

interface PaymentGatewayContract
{
    /**
     * Returns the PSP checkout URL
     * 
     * @param Order $order the pending order 
     * @param CheckoutToken $token the secure token generated by the `CheckoutService`
     * @return string the URL
     */
    public function createCheckoutSession(Order $order, CheckoutToken $token): string;

    /**
     * Handle the incoming webhook from the PSP
     * 
     * @param Request $request the HTTP request from the PSP
     * 
     * @throws Exception
     */
    public function handleCallback(Request $request): PaymentResult;
}